package java_morse;

import java.util.Scanner;

/**
 * The user must be allowed to enter more than one world so the main method
 * must provide a solution of the exceptions generated by the Scanner when the user insert a whitespace.
 * A Scanner breaks its input into tokens using a delimiter pattern, which by default matches whitespace.
 * On line 15, it changes the delimiter of Scanner to another pattern such as a line feed or something else.
 */
public class JMain {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        scanner.useDelimiter("\n");
        JMorse m = new JMorse();

        int s = 0;
        do {
            System.out.print("\n\n|Morse code translator|\n0) Exit\n1) Translate the text\n2) Print Morse translation\n" +
                    "Number: ");
            s = scanner.nextInt();

            switch (s) {
                case 0: System.out.println("Good bye!");
                break;
                case 1: {
                    System.out.print("Input the message: ");
                    String text = scanner.next();
                    m.fillText(text);
                }
                break;
                case 2: m.printMorse();
                    break;
                default:
                    System.out.println("I can't do nothing whit this number");
            }
        } while(s != 0);
    }
}